name: blood1
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #sqflite: ^1.0.0
  #path_provider: ^0.4.1
  pin_code_fields: ^6.0.0
  splashscreen: ^1.3.5
  cupertino_icons: ^1.0.0
  adobe_xd: ^1.0.0+1
  provider: ^4.3.3
  google_fonts: ^1.0.0
  flutter_typeahead: ^2.0.0
  shared_preferences: ^0.5.12+4
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/

  #   - images/a_dot_ham.jpeg


    # example:
  #fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
